### ISSUE TITLE
new MSP432 cores available

### ISSUE THREAD

**Issue by ndroid** [Andy4495/TI_Platform_Cores_For_Arduino#1]
I have created a new project to maintain and extend the msp432 core from Energia to work with Arduino. It is built upon v5.29.1, which did not suffer from the same complications of using with Arduino or in Windows as did v5.29.0. It uses ino2cpp 1.0.7 rather than 1.0.6, and does not depend on any java references. It also adds support for the MSP432P4111 board, includes bug fixes, and extends functionality. The package index file can be found in the root directory of the following repo: [msp432-core](https://github.com/ndroid/msp432-core)

The board package file is in the _cores_ directory, and full source is provided in the _src_ directory. 

I can put together a pull request if that would be desired.

**Comment by Andy4495** [comment]
Thanks for this - I'll get the updated MSP432 files added and make the appropriate updates to the README. It's great to see continuing development with this despite the demise of Energia.

**Comment by ndroid** [comment]
Likewise, thanks for your effort to maintain and keep the Energia platforms available.
