### ISSUE TITLE
Usage in PlatformIO

### ISSUE THREAD

**Issue by chemmex** [Andy4495/TI_Platform_Cores_For_Arduino#3]
Can these cores be used with Platformio?

**Comment by Andy4495** [comment]
I don't know; I don't use platformIO and haven't tested them. However, if platformIO uses other cores unmodified, then these should also work. 

You can always try to load them and see. If you do, let me know and I'll update the README.

**Comment by rei-vilo** [comment]
Platformio already supports the TivaC TM4C123 and TM4C129. 

See https://registry.platformio.org/platforms/platformio/titiva

**Comment by chemmex** [comment]
Thanks for your comments. Actually, I just meant using msp430_elf_GCC package in the Platformio as I prefer it over Arduino/Energia IDE.
Eventually I found out that simple sketch for MSP430G2553 which uses standard SoftSerial lib cannot fit 512 bytes of RAM when compiled with msp430_elf_GCC, so I would revert to the old compiler and will try to adjust the lib I use.

**Comment by rei-vilo** [comment]
Platformio lists all these [TI MSP430 boards](https://docs.platformio.org/en/latest/boards/index.html#ti-msp430) but I don't know which tool-chain there are using.

For a very compact binary code, I am still using [Energia release 0101E0012](https://[energia.nu/download/](https://energia.nu/download/).

Obviously, I am not using the Arduino / Energia IDE, but Visual Studio Code with [emCode](https://github.com/rei-vilo/emcode).

**Comment by Andy4495** [comment]
Since my focus is on Arduino compatibility and it appears that you are taking an alternate route on the original request, I am going to close this.

**Comment by chemmex** [comment]
I have found a possible way to use msp430-elf-gcc 9.2.0.50 compler and MSP430 2.0.12 board package with Platformio on a per-project basis:
I had to download the toolchain and board packages using links from [this file](http://s3.amazonaws.com/energiaUS/packages/package_msp430_elf_GCC_index.json), unpack them and add respective package.json files (I used platformio files of standard packages as an example). 

Then I added the **platform_packages =**  option into the project's platformio.ini file with links to local files:
```
[env:lpmsp430fr5969]
platform = timsp430
board = lpmsp430fr5969
framework = arduino
platform_packages = 
            framework-energiamsp430-elf@file:///home/chemmex/Downloads/framework-energiamsp430-elf
            toolchain-timsp430-elf@file:///home/chemmex/Downloads/toolchain-timsp430-elf
lib_deps = 
            https://github.com/adafruit/Adafruit_NeoPixel
```

Then Platformio compiled the project using msp430-elf-gcc.

More info can be found [here](https://community.platformio.org/t/using-different-toolchain-versions/22787)

**Comment by Andy4495** [comment]
Great - I'm glad you were able to get this working. I added a note in my README with this info in case somebody else comes across this. Thanks.
