### ISSUE TITLE
RTOS high-level library for MSP432

### ISSUE THREAD

**Issue by rei-vilo** [Andy4495/TI_Platform_Cores_For_Arduino#4]
One of the key features of Energia for the MSP432 is the full support of TI-RTOS.

To make the use of RTOS easier, I have developed the **Galaxia library**, which encapsulates the main RTOS elements as objects: 

- Threads elements: HWI, Task
- Synchronisation elements: Event, Semaphore, Mailbox, Clock
- Reference: https://github.com/rei-vilo/Galaxia_Library
  
The Galaxia library also runs boards supported by Energia MT:

- No IoT: LaunchPad MSP432P401R and MSP432P4111
- sub-1 GHz: LaunchPad CC1310 and CC1312
- BLE + sub-1 GHz: LaunchPad CC1350 and CC1352, LPSTK-CC1352
- BLE: LaunchPad CC2652
- WiFi: LaunchPad CC3200, CC3220, CC3235
- Ethernet: LaunchPad MSP432E401Y

Feel free to include it among the default libraries of the board package.

**Comment by Andy4495** [comment]
I updated the README to include references to Galaxia. I currently don't have plans to update the MSP432 board package, but I see @ndroid liked your comment, so they may add it in a future update.
