### ISSUE TITLE
TivaC LaunchPad TM4C123G upload failed

### ISSUE THREAD

**Issue by Josef287** [Andy4495/TI_Platform_Cores_For_Arduino#5]
With the arduino IDE the code upload to the TivaC LaunchPad TM4C123G failed.
Error message is:

Sketch uses 2628 bytes (1%) of program storage space. Maximum is 262144 bytes.
Global variables use 520 bytes (1%) of dynamic memory, leaving 32248 bytes for local variables. Maximum is 32768 bytes.
DSLite version 9.3.0.1863
Configuring Debugger (may take a few minutes on first launch)...
	Initializing Register Database...
	Initializing: CORTEX_M4_0
	Executing Startup Scripts: CORTEX_M4_0
GEL: CORTEX_M4_0: GEL Output: 
Memory Map Initialization Complete
Connecting...
error: CORTEX_M4_0: Error connecting to the target: Unable to communicate with the device. Please check your connection.
Failed to load dynamic library: 'ftd2xx.dll'
Failed to load dynamic library: 'ftd2xx.dll'
Failed to load dynamic library: 'ftd2xx.dll'
Failed to load dynamic library: 'ftd2xx.dll'
Failed to load dynamic library: 'ftd2xx.dll'
Failed to load dynamic library: 'ftd2xx.dll'
Failed: Operation was aborted
Failed uploading: uploading error: exit status 1

**Comment by Andy4495** [comment]
I assume you are getting this on a Windows machine (since the error is about a DLL). 

Go to this link: https://energia.nu/guide/install/windows/ and follow the instructions under the `EK-TM4C123GXL, EK-TM4C1294XL and EK-LM4F120XL LaunchPad` heading.

Hopefully that fixes it.
